# Production Profile
spring:
  profiles:
    active: production
  application:
    name: Master Mind
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/mastermind
    username: root
    password: ""
logging:
  file: log/master-mind.log

server:
  compression:
    enabled: true
  servlet:
    context-path: /mastermind
