version: '3.2'

services:
  coding-camp-2019-production-db:
    image: 1000kit/h2
    container_name: coding-camp-2019-production-db
    restart: always
    networks:
      - coding-camp-2019-production
    volumes:
      - "h2-data:/opt/h2-data"

  coding-camp-2019-app:
    image: coding-camp.artifactory.sybit.de/coding-camp-2019:latest
    container_name: coding-camp-2019-production-app
    restart: always
    ports:
      - "8282:8080"
    depends_on:
      - coding-camp-2019-production-db
    networks:
      - coding-camp-2019-production
    volumes:
      - "log:/app/log/"
    environment:
      spring.profiles.active: production
      TZ: Europe/Berlin

networks:
  coding-camp-2019-production:
    external: false
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.254/16

volumes:
  h2-data:
  log:
